# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/uart_constraints.xdc

# Block Designs: bd/QC_IntegrationTest/QC_IntegrationTest.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QC_IntegrationTest || ORIG_REF_NAME==QC_IntegrationTest} -quiet] -quiet

# IP: bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/QC_IntegrationTest_xdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_xdma_0_0 || ORIG_REF_NAME==QC_IntegrationTest_xdma_0_0} -quiet] -quiet

# IP: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_2/xdma_v4_1_23_blk_mem_64_noreg_be.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_23_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_1_23_blk_mem_64_noreg_be} -quiet] -quiet

# IP: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_1/xdma_v4_1_23_blk_mem_64_reg_be.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_23_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_1_23_blk_mem_64_reg_be} -quiet] -quiet

# IP: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/QC_IntegrationTest_xdma_0_0_pcie4_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_xdma_0_0_pcie4_ip || ORIG_REF_NAME==QC_IntegrationTest_xdma_0_0_pcie4_ip} -quiet] -quiet

# IP: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/ip_0/QC_IntegrationTest_xdma_0_0_pcie4_ip_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_xdma_0_0_pcie4_ip_gt || ORIG_REF_NAME==QC_IntegrationTest_xdma_0_0_pcie4_ip_gt} -quiet] -quiet

# IP: bd/QC_IntegrationTest/ip/QC_IntegrationTest_complex_signal_gener_0_0/QC_IntegrationTest_complex_signal_gener_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_complex_signal_gener_0_0 || ORIG_REF_NAME==QC_IntegrationTest_complex_signal_gener_0_0} -quiet] -quiet

# IP: bd/QC_IntegrationTest/ip/QC_IntegrationTest_xlconcat_0_0/QC_IntegrationTest_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_xlconcat_0_0 || ORIG_REF_NAME==QC_IntegrationTest_xlconcat_0_0} -quiet] -quiet

# IP: bd/QC_IntegrationTest/ip/QC_IntegrationTest_xlconstant_0_0/QC_IntegrationTest_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_xlconstant_0_0 || ORIG_REF_NAME==QC_IntegrationTest_xlconstant_0_0} -quiet] -quiet

# IP: bd/QC_IntegrationTest/ip/QC_IntegrationTest_xlconstant_1_0/QC_IntegrationTest_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_xlconstant_1_0 || ORIG_REF_NAME==QC_IntegrationTest_xlconstant_1_0} -quiet] -quiet

# IP: bd/QC_IntegrationTest/ip/QC_IntegrationTest_xlconstant_2_0/QC_IntegrationTest_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_xlconstant_2_0 || ORIG_REF_NAME==QC_IntegrationTest_xlconstant_2_0} -quiet] -quiet

# IP: bd/QC_IntegrationTest/ip/QC_IntegrationTest_axis_data_fifo_0_0/QC_IntegrationTest_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_axis_data_fifo_0_0 || ORIG_REF_NAME==QC_IntegrationTest_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/QC_IntegrationTest/ip/QC_IntegrationTest_ila_0_1/QC_IntegrationTest_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_ila_0_1 || ORIG_REF_NAME==QC_IntegrationTest_ila_0_1} -quiet] -quiet

# IP: bd/QC_IntegrationTest/ip/QC_IntegrationTest_ila_0_2/QC_IntegrationTest_ila_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_ila_0_2 || ORIG_REF_NAME==QC_IntegrationTest_ila_0_2} -quiet] -quiet

# IP: bd/QC_IntegrationTest/ip/QC_IntegrationTest_util_ds_buf2_1/QC_IntegrationTest_util_ds_buf2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_util_ds_buf2_1 || ORIG_REF_NAME==QC_IntegrationTest_util_ds_buf2_1} -quiet] -quiet

# IP: bd/QC_IntegrationTest/ip/QC_IntegrationTest_zynq_ultra_ps_e_0_0/QC_IntegrationTest_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==QC_IntegrationTest_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/QC_IntegrationTest/ip/QC_IntegrationTest_proc_sys_reset_0_0/QC_IntegrationTest_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_proc_sys_reset_0_0 || ORIG_REF_NAME==QC_IntegrationTest_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/QC_IntegrationTest/ip/QC_IntegrationTest_xbar_1/QC_IntegrationTest_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_xbar_1 || ORIG_REF_NAME==QC_IntegrationTest_xbar_1} -quiet] -quiet

# IP: bd/QC_IntegrationTest/ip/QC_IntegrationTest_ps8_0_axi_periph_1/QC_IntegrationTest_ps8_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_ps8_0_axi_periph_1 || ORIG_REF_NAME==QC_IntegrationTest_ps8_0_axi_periph_1} -quiet] -quiet

# IP: bd/QC_IntegrationTest/ip/QC_IntegrationTest_axi_gpio_0_0/QC_IntegrationTest_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_axi_gpio_0_0 || ORIG_REF_NAME==QC_IntegrationTest_axi_gpio_0_0} -quiet] -quiet

# IP: bd/QC_IntegrationTest/ip/QC_IntegrationTest_axi_quad_spi_0_0/QC_IntegrationTest_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_axi_quad_spi_0_0 || ORIG_REF_NAME==QC_IntegrationTest_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/QC_IntegrationTest/ip/QC_IntegrationTest_auto_pc_0/QC_IntegrationTest_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_auto_pc_0 || ORIG_REF_NAME==QC_IntegrationTest_auto_pc_0} -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_2/xdma_v4_1_23_blk_mem_64_noreg_be_ooc.xdc

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_1/xdma_v4_1_23_blk_mem_64_reg_be_ooc.xdc

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/ip_0/synth/QC_IntegrationTest_xdma_0_0_pcie4_ip_gt_ooc.xdc

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/ip_0/synth/QC_IntegrationTest_xdma_0_0_pcie4_ip_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_xdma_0_0_pcie4_ip_gt || ORIG_REF_NAME==QC_IntegrationTest_xdma_0_0_pcie4_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/QC_IntegrationTest_xdma_0_0_pcie4_ip_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_xdma_0_0_pcie4_ip || ORIG_REF_NAME==QC_IntegrationTest_xdma_0_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/ip_pcie4_uscale_plus_impl_x1y0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_xdma_0_0_pcie4_ip || ORIG_REF_NAME==QC_IntegrationTest_xdma_0_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/synth/QC_IntegrationTest_xdma_0_0_pcie4_ip_ooc.xdc

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/synth/QC_IntegrationTest_xdma_0_0_pcie4_ip_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_xdma_0_0_pcie4_ip || ORIG_REF_NAME==QC_IntegrationTest_xdma_0_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/ip_pcie4_uscale_plus_x1y0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_xdma_0_0_pcie4_ip || ORIG_REF_NAME==QC_IntegrationTest_xdma_0_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/QC_IntegrationTest_xdma_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_xdma_0_0 || ORIG_REF_NAME==QC_IntegrationTest_xdma_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/source/QC_IntegrationTest_xdma_0_0_pcie4_uscaleplus_ip.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_xdma_0_0 || ORIG_REF_NAME==QC_IntegrationTest_xdma_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/synth/QC_IntegrationTest_xdma_0_0_ooc.xdc

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_ila_0_1 || ORIG_REF_NAME==QC_IntegrationTest_ila_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_ila_0_1/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_ila_0_1 || ORIG_REF_NAME==QC_IntegrationTest_ila_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_ila_0_1/QC_IntegrationTest_ila_0_1_ooc.xdc

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_ila_0_2/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_ila_0_2 || ORIG_REF_NAME==QC_IntegrationTest_ila_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_ila_0_2/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_ila_0_2 || ORIG_REF_NAME==QC_IntegrationTest_ila_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_ila_0_2/QC_IntegrationTest_ila_0_2_ooc.xdc

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_util_ds_buf2_1/QC_IntegrationTest_util_ds_buf2_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_util_ds_buf2_1 || ORIG_REF_NAME==QC_IntegrationTest_util_ds_buf2_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_util_ds_buf2_1/QC_IntegrationTest_util_ds_buf2_1_ooc.xdc

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_zynq_ultra_ps_e_0_0/QC_IntegrationTest_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_zynq_ultra_ps_e_0_0/QC_IntegrationTest_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==QC_IntegrationTest_zynq_ultra_ps_e_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_proc_sys_reset_0_0/QC_IntegrationTest_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_proc_sys_reset_0_0 || ORIG_REF_NAME==QC_IntegrationTest_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_proc_sys_reset_0_0/QC_IntegrationTest_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_proc_sys_reset_0_0 || ORIG_REF_NAME==QC_IntegrationTest_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_axi_gpio_0_0/QC_IntegrationTest_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_axi_gpio_0_0 || ORIG_REF_NAME==QC_IntegrationTest_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_axi_gpio_0_0/QC_IntegrationTest_axi_gpio_0_0_ooc.xdc

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_axi_gpio_0_0/QC_IntegrationTest_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_axi_gpio_0_0 || ORIG_REF_NAME==QC_IntegrationTest_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_axi_quad_spi_0_0_1/QC_IntegrationTest_axi_quad_spi_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_axi_quad_spi_0_0 || ORIG_REF_NAME==QC_IntegrationTest_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_axi_quad_spi_0_0_1/QC_IntegrationTest_axi_quad_spi_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_axi_quad_spi_0_0 || ORIG_REF_NAME==QC_IntegrationTest_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_axi_quad_spi_0_0_1/QC_IntegrationTest_axi_quad_spi_0_0_ooc.xdc

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_axi_quad_spi_0_0_1/QC_IntegrationTest_axi_quad_spi_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==QC_IntegrationTest_axi_quad_spi_0_0 || ORIG_REF_NAME==QC_IntegrationTest_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_auto_pc_0/QC_IntegrationTest_auto_pc_0_ooc.xdc

# XDC: c:/Xilinx/Projects/Xilinx_ZU19EG_PCIe/ZU19_PCIe_AXI_STREAM - iWaveRef/Vivado2023.1/UARTECHO.gen/sources_1/bd/QC_IntegrationTest/QC_IntegrationTest_ooc.xdc
