#!/bin/bash -f
#**********************************************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Script generated by Vivado on Thu May 29 16:02:37 -0400 2025
# SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
#
# Tool Version Limit: 2023.05 
#
# Filename     : QC_IntegrationTest.sh
# Simulator    : Synopsys Verilog Compiler Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : QC_IntegrationTest.sh
#                QC_IntegrationTest.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                QC_IntegrationTest.sh [-reset_run]
#                QC_IntegrationTest.sh [-reset_log]
#                QC_IntegrationTest.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the Xilinx simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'QC_IntegrationTest.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set vhdlan compile options
vhdlan_opts="-full64 -l .tmp_log"

# set vlogan compile options
vlogan_opts="-full64 -l .tmp_log"

# set vcs elaboration options
vcs_elab_opts="-full64 -t ps -licqueue -l elaborate.log"

# set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# set design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_14 zynq_ultra_ps_e_vip_v1_0_14 xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 dist_mem_gen_v8_0_13 lib_pkg_v1_0_2 lib_srl_fifo_v1_0_2 fifo_generator_v13_2_8 lib_fifo_v1_0_17 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_quad_spi_v3_2_27 axi_gpio_v2_0_30 gtwizard_ultrascale_v1_7_16 blk_mem_gen_v8_4_6 xdma_v4_1_23 xlconcat_v2_1_4 xlconstant_v1_1_7 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_28 axi_data_fifo_v2_1_27 axi_crossbar_v2_1_29 axis_infrastructure_v1_1_0 axis_data_fifo_v2_0_10 axi_protocol_converter_v2_1_28)

# simulation root library directory
sim_lib_dir="vcs_lib"

# script info
echo -e "QC_IntegrationTest.sh - Script generated by export_simulation (Vivado v2023.1 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./QC_IntegrationTest.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "C:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "C:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "C:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "C:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "C:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "C:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > vlogan.log 2>/dev/null

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "C:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "C:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "C:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xpm $vhdlan_opts \
  "C:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > vhdlan.log 2>/dev/null

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_vip_v1_1_14 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ed63/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work zynq_ultra_ps_e_vip_v1_0_14 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_zynq_ultra_ps_e_0_0/sim/QC_IntegrationTest_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_proc_sys_reset_0_0/sim/QC_IntegrationTest_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work dist_mem_gen_v8_0_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/0bf5/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work fifo_generator_v13_2_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/c97d/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work fifo_generator_v13_2_8 $vhdlan_opts \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/c97d/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work fifo_generator_v13_2_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/c97d/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work lib_fifo_v1_0_17 $vhdlan_opts \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/3d41/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work axi_quad_spi_v3_2_27 $vhdlan_opts \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/3799/hdl/axi_quad_spi_v3_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_axi_quad_spi_0_0/sim/QC_IntegrationTest_axi_quad_spi_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work axi_gpio_v2_0_30 $vhdlan_opts \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/18b7/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_axi_gpio_0_0/sim/QC_IntegrationTest_axi_gpio_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work gtwizard_ultrascale_v1_7_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/ip_0/sim/gtwizard_ultrascale_v1_7_gthe4_channel.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/ip_0/sim/QC_IntegrationTest_xdma_0_0_pcie4_ip_gt_gthe4_channel_wrapper.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/ip_0/sim/QC_IntegrationTest_xdma_0_0_pcie4_ip_gt_gtwizard_gthe4.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/ip_0/sim/QC_IntegrationTest_xdma_0_0_pcie4_ip_gt_gtwizard_top.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/ip_0/sim/QC_IntegrationTest_xdma_0_0_pcie4_ip_gt.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_gtwizard_top.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_phy_ff_chain.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_phy_pipeline.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_bram_16k_int.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_bram_16k.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_bram_32k.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_bram_4k_int.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_bram_msix.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_bram_rep_int.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_bram_rep.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_bram_tph.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_bram.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_gt_gt_channel.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_gt_gt_common.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_gt_phy_clk.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_gt_phy_rst.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_gt_phy_rxeq.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_gt_phy_txeq.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_sync_cell.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_sync.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_gt_cdr_ctrl_on_eidle.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_gt_receiver_detect_rxterm.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_gt_phy_wrapper.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_init_ctrl.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_pl_eq.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_vf_decode.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_pipe.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_phy_top.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_seqnum_fifo.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_sys_clk_gen_ps.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source/QC_IntegrationTest_xdma_0_0_pcie4_ip_pcie4_uscale_core_top.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/sim/QC_IntegrationTest_xdma_0_0_pcie4_ip.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work blk_mem_gen_v8_4_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/bb55/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_1/sim/xdma_v4_1_23_blk_mem_64_reg_be.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_2/sim/xdma_v4_1_23_blk_mem_64_noreg_be.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xdma_v4_1_23 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/xdma_v4_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/xdma_v4_1/hdl/verilog/QC_IntegrationTest_xdma_0_0_dma_bram_wrap.sv" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/xdma_v4_1/hdl/verilog/QC_IntegrationTest_xdma_0_0_dma_bram_wrap_1024.sv" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/xdma_v4_1/hdl/verilog/QC_IntegrationTest_xdma_0_0_dma_bram_wrap_2048.sv" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/xdma_v4_1/hdl/verilog/QC_IntegrationTest_xdma_0_0_core_top.sv" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/sim/QC_IntegrationTest_xdma_0_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_complex_signal_gener_0_0/sim/QC_IntegrationTest_complex_signal_gener_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xlconcat_0_0/sim/QC_IntegrationTest_xlconcat_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/b0f2/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xlconstant_0_0/sim/QC_IntegrationTest_xlconstant_0_0.v" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xlconstant_1_0/sim/QC_IntegrationTest_xlconstant_1_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_util_ds_buf_1/util_ds_buf.vhd" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_util_ds_buf_1/sim/QC_IntegrationTest_util_ds_buf_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xlconstant_2_0/sim/QC_IntegrationTest_xlconstant_2_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_register_slice_v2_1_28 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/87d1/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_data_fifo_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/fab7/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_crossbar_v2_1_29 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f8f3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xbar_1/sim/QC_IntegrationTest_xbar_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axis_data_fifo_v2_0_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8eca/hdl/axis_data_fifo_v2_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_axis_data_fifo_0_0/sim/QC_IntegrationTest_axis_data_fifo_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_ila_0_1/sim/QC_IntegrationTest_ila_0_1.vhd" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_ila_0_2/sim/QC_IntegrationTest_ila_0_2.vhd" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_util_ds_buf_2/sim/QC_IntegrationTest_util_ds_buf_2.vhd" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_util_ds_buf1_0/sim/QC_IntegrationTest_util_ds_buf1_0.vhd" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_util_ds_buf1_1/sim/QC_IntegrationTest_util_ds_buf1_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work axi_protocol_converter_v2_1_28 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8c02/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/ec67/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/f805/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ip/QC_IntegrationTest_xdma_0_0/ip_0/source" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/03b2/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/8713/hdl" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/1b7e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/122e/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/affe/hdl/verilog" +incdir+"../../../../UARTECHO.gen/sources_1/bd/QC_IntegrationTest/ipshared/20d0/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/QC_IntegrationTest/ip/QC_IntegrationTest_auto_pc_0/sim/QC_IntegrationTest_auto_pc_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/QC_IntegrationTest/sim/QC_IntegrationTest.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.QC_IntegrationTest xil_defaultlib.glbl -o QC_IntegrationTest_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./QC_IntegrationTest_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file


  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key QC_IntegrationTest_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log lib_sc.so 64 AN.DB csrc QC_IntegrationTest_simv.daidir vcs_lib c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./QC_IntegrationTest.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: QC_IntegrationTest.sh [-help]\n\
Usage: QC_IntegrationTest.sh [-step]\n\
Usage: QC_IntegrationTest.sh [-lib_map_path]\n\
Usage: QC_IntegrationTest.sh [-reset_run]\n\
Usage: QC_IntegrationTest.sh [-reset_log]\n\
Usage: QC_IntegrationTest.sh [-keep_index]\n\
Usage: QC_IntegrationTest.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (compile, elaborate, simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
